# .streamlit/secrets.toml
# 在本地開發或部署到 Streamlit Cloud 時，透過 st.secrets 讀取。

# FinMind 台股 API Token
FINMIND_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyNS0wNy0yMyAyMjo0MDoyMSIsInVzZXJfaWQiOiJrYW5nIiwiaXAiOiIzNi4yMzcuMTk3LjE1NiJ9.Y5WYLBBHfVe0jBGJyvJi567EQrNw7PetyBZW-ZWtmm8"

# （可選）其他私密設定
# OPENAI_API_KEY = "如果日後要串 GPT，再貼在這"
# DB_PASSWORD     = "你的資料庫密碼"
